FROM eclipse-temurin:17-jdk AS build
WORKDIR /workspace

COPY . .
RUN chmod +x gradlew && ./gradlew :hanyang-api:bootJar -x test

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /workspace/hanyang-api/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
