spring:
  application:
    name: hanyang-user-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - optional:classpath:/application-core.yaml

cors:
  allowed-origins: https://hanyang.life,https://admin.hanyang.life

server:
  port: 8080
