spring:
  application:
    name: hanyang-admin-api
  config:
    import:
      - optional:classpath:/application-core.yaml

admin:
  auth:
    jwt:
      secret: ${ADMIN_JWT_SECRET}
      expiration-ms: ${ADMIN_JWT_EXPIRATION:3600000}
    accounts:
      - username: ${ADMIN_ID_1}
        password: ${ADMIN_PASSWORD_1}
      - username: ${ADMIN_ID_2}
        password: ${ADMIN_PASSWORD_2}

cors:
  allowed-origins: https://hanyang.life,https://admin.hanyang.life

server:
  port: 8081
